### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by vv521** [FlagAlpha/Llama2-Chinese#104]
python examples/chat_gradio.py --model_name_or_path meta-llama/Llama-2-7b-chat-hf

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin E:\Anconda\envs\Llama2\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so
False
E:\Anconda\envs\Llama2\lib\site-packages\bitsandbytes\cuda_setup\main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPat
h('E'), WindowsPath('/Anconda/envs/Llama2/lib')}
  warn(msg)
E:\Anconda\envs\Llama2\lib\site-packages\bitsandbytes\cuda_setup\main.py:149: UserWarning: E:\Anconda\envs\Llama2 did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0']
 as expected! Searching further paths...
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
E:\Anconda\envs\Llama2\lib\site-packages\bitsandbytes\cuda_setup\main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPat
h('/usr/local/cuda/lib64')}
  warn(msg)
CUDA SETUP: WARNING! libcuda.so not found! Do you have a CUDA driver installed? If you are on a cluster, make sure you are on a CUDA machine!
E:\Anconda\envs\Llama2\lib\site-packages\bitsandbytes\cuda_setup\main.py:149: UserWarning: WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)!
  warn(msg)
E:\Anconda\envs\Llama2\lib\site-packages\bitsandbytes\cuda_setup\main.py:149: UserWarning: WARNING: No GPU detected! Check your CUDA paths. Proceeding to load CPU-only library...
  warn(msg)
CUDA SETUP: Loading binary E:\Anconda\envs\Llama2\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
argument of type 'WindowsPath' is not iterable
CUDA SETUP: Problem: The main issue seems to be that the main CUDA library was not detected.
CUDA SETUP: Solution 1): Your paths are probably not up-to-date. You can update them via: sudo ldconfig.
CUDA SETUP: Solution 2): If you do not have sudo rights, you can do the following:
CUDA SETUP: Solution 2a): Find the cuda library via: find / -name libcuda.so 2>/dev/null
CUDA SETUP: Solution 2b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_2a
CUDA SETUP: Solution 2c): For a permanent solution add the export from 2b into your .bashrc file, located at ~/.bashrc
Traceback (most recent call last):
  File "E:\Anconda\envs\Llama2\lib\site-packages\transformers\utils\import_utils.py", line 1099, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "E:\Anconda\envs\Llama2\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\Anconda\envs\Llama2\lib\site-packages\transformers\models\llama\modeling_llama.py", line 32, in <module>
    from ...modeling_utils import PreTrainedModel
  File "E:\Anconda\envs\Llama2\lib\site-packages\transformers\modeling_utils.py", line 86, in <module>
    from accelerate import dispatch_model, infer_auto_device_map, init_empty_weights
  File "E:\Anconda\envs\Llama2\lib\site-packages\accelerate\__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "E:\Anconda\envs\Llama2\lib\site-packages\accelerate\accelerator.py", line 35, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "E:\Anconda\envs\Llama2\lib\site-packages\accelerate\checkpointing.py", line 24, in <module>
    from .utils import (
  File "E:\Anconda\envs\Llama2\lib\site-packages\accelerate\utils\__init__.py", line 131, in <module>
    from .bnb import has_4bit_bnb_layers, load_and_quantize_model
  File "E:\Anconda\envs\Llama2\lib\site-packages\accelerate\utils\bnb.py", line 42, in <module>
    import bitsandbytes as bnb
  File "E:\Anconda\envs\Llama2\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "E:\Anconda\envs\Llama2\lib\site-packages\bitsandbytes\research\__init__.py", line 1, in <module>
    from . import nn
  File "E:\Anconda\envs\Llama2\lib\site-packages\bitsandbytes\research\nn\__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "E:\Anconda\envs\Llama2\lib\site-packages\bitsandbytes\research\nn\modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "E:\Anconda\envs\Llama2\lib\site-packages\bitsandbytes\optim\__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "E:\Anconda\envs\Llama2\lib\site-packages\bitsandbytes\cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError:
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "H:\Llama2-Chinese-main\examples\chat_gradio.py", line 94, in <module>
    model = AutoModelForCausalLM.from_pretrained(args.model_name_or_path, device_map='auto',
  File "E:\Anconda\envs\Llama2\lib\site-packages\transformers\models\auto\auto_factory.py", line 492, in from_pretrained
    model_class = _get_model_class(config, cls._model_mapping)
  File "E:\Anconda\envs\Llama2\lib\site-packages\transformers\models\auto\auto_factory.py", line 376, in _get_model_class
    supported_models = model_mapping[type(config)]
  File "E:\Anconda\envs\Llama2\lib\site-packages\transformers\models\auto\auto_factory.py", line 666, in __getitem__
    return self._load_attr_from_module(model_type, model_name)
  File "E:\Anconda\envs\Llama2\lib\site-packages\transformers\models\auto\auto_factory.py", line 680, in _load_attr_from_module
    return getattribute_from_module(self._modules[module_name], attr)
  File "E:\Anconda\envs\Llama2\lib\site-packages\transformers\models\auto\auto_factory.py", line 625, in getattribute_from_module
    if hasattr(module, attr):
  File "E:\Anconda\envs\Llama2\lib\site-packages\transformers\utils\import_utils.py", line 1089, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "E:\Anconda\envs\Llama2\lib\site-packages\transformers\utils\import_utils.py", line 1101, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.llama.modeling_llama because of the following error (look up to see its traceback):

        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

**Comment by rufeng-h** [comment]
这个我也遇到了，把bitsandbytes源码拉下来参照CUDA版本编译安装就好了
