### ISSUE TITLE
按照《手把手教你部署Llama2》部署跑不起来

### ISSUE THREAD

**Issue by mmhzlrj** [FlagAlpha/Llama2-Chinese#109]
C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
'NoneType' object has no attribute 'cadam32bit_grad_fp32'
Traceback (most recent call last):
  File "C:\Llama2-Chinese\examples\chat_gradio.py", line 86, in <module>
    model = AutoModelForCausalLM.from_pretrained(args.model_name_or_path,device_map='auto',torch_dtype=torch.float16,load_in_8bit=True)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\models\auto\auto_factory.py", line 493, in from_pretrained
    return model_class.from_pretrained(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\modeling_utils.py", line 2474, in from_pretrained
    raise EnvironmentError(
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory C:\Llama2-Chinese\Llama-2-7b-chat

**Comment by Rayrtfr** [comment]
下载的模型错误，应该下载huggingface的版本
<img width="1079" alt="image" src="https://github.com/FlagAlpha/Llama2-Chinese/assets/139932418/e62f0886-e75a-435e-a39d-dc2735652d3d">
