### ISSUE TITLE
chat_gradio.报错 Some modules are dispatched on the CPU or the disk

### ISSUE THREAD

**Issue by heiheiheibj** [FlagAlpha/Llama2-Chinese#123]
WINDOWS2016的机器，TESLA T4 16G显存，CUDA11.8

报错信息如下

(llama2) C:\Llama2-Chinese>python examples/chat_gradio.py --model_name_or_path C:\Llama2-Chinese\model\Llama-2-7b-chat-hf
C:\ProgramData\anaconda3\envs\llama2\lib\site-packages\bitsandbytes\cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
'NoneType' object has no attribute 'cadam32bit_grad_fp32'
Traceback (most recent call last):
  File "C:\Llama2-Chinese\examples\chat_gradio.py", line 86, in <module>
    model = AutoModelForCausalLM.from_pretrained(args.model_name_or_path,device_map='auto',torch_dtype=torch.float16,load_in_8bit=True)
  File "C:\ProgramData\anaconda3\envs\llama2\lib\site-packages\transformers\models\auto\auto_factory.py", line 493, in from_pretrained
    return model_class.from_pretrained(
  File "C:\ProgramData\anaconda3\envs\llama2\lib\site-packages\transformers\modeling_utils.py", line 2842, in from_pretrained
    raise ValueError(
ValueError:
                        Some modules are dispatched on the CPU or the disk. Make sure you have enough GPU RAM to fit
                        the quantized model. If you want to dispatch the model on the CPU or the disk while keeping
                        these modules in 32-bit, you need to set `load_in_8bit_fp32_cpu_offload=True` and pass a custom
                        `device_map` to `from_pretrained`. Check
                        https://huggingface.co/docs/transformers/main/en/main_classes/quantization#offload-between-cpu-and-gpu
                        for more details.

如何解决呢，谢谢

**Comment by denglq** [comment]
同问

**Comment by czw-czw-czw** [comment]
同问

**Comment by czw-czw-czw** [comment]
@Rayrtfr
