### ISSUE TITLE
examples/chat_gradio.py 如何加载GPTQ的量化模型

### ISSUE THREAD

**Issue by heiheiheibj** [FlagAlpha/Llama2-Chinese#147]
下载了 https://huggingface.co/FlagAlpha/Llama2-Chinese-13b-Chat-4bit/
用 AutoGPTQ 可以直接加载正常使用，用 examples/chat_gradio.py 报错

CUDA SETUP: Loading binary /root/anaconda3/envs/llama2/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118.so...
Traceback (most recent call last):
  File "/usr/local/Llama2-Chinese/examples/chat_gradio.py", line 86, in <module>
    model = AutoModelForCausalLM.from_pretrained(args.model_name_or_path,device_map='auto',torch_dtype=torch.float16,load_in_8bit=True)
  File "/root/anaconda3/envs/llama2/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 493, in from_pretrained
    return model_class.from_pretrained(
  File "/root/anaconda3/envs/llama2/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2474, in from_pretrained
    raise EnvironmentError(
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory /usr/local/Llama2-Chinese/Llama2-Chinese-13b-Chat-4bit.

谢谢

**Comment by ZHangZHengEric** [comment]
在启动的时候，加上4bit 量化的参数，具体可以参考readme
