### ISSUE TITLE
deepspeed 安装报错

### ISSUE THREAD

**Issue by vijaygao** [FlagAlpha/Llama2-Chinese#168]
# pip3 install deepspeed
Collecting deepspeed
  Downloading deepspeed-0.10.2.tar.gz (858 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 858.2/858.2 kB 12.8 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-n7q5q2ea/deepspeed_764ee70823304e0a82a71c4c788744d7/setup.py", line 100, in <module>
          cuda_major_ver, cuda_minor_ver = installed_cuda_version()
        File "/tmp/pip-install-n7q5q2ea/deepspeed_764ee70823304e0a82a71c4c788744d7/op_builder/builder.py", line 41, in installed_cuda_version
          assert cuda_home is not None, "CUDA_HOME does not exist, unable to compile CUDA op(s)"
      AssertionError: CUDA_HOME does not exist, unable to compile CUDA op(s)
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by vijaygao** [comment]
有部署成功的docker镜像嘛？

**Comment by ZHangZHengEric** [comment]
感觉好像是没有安装cuda

**Comment by telunyang** [comment]
如果確定有安裝好 CUDA (例如 11.x)，可以參考如下設定:
```bash
export CUDA_HOME=/usr/local/cuda
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/cuda/lib64
export PATH=${PATH}:/usr/local/cuda/bin
```
