### ISSUE TITLE
对Llama-2-7b-chat-hf模型进行预训练出错

### ISSUE THREAD

**Issue by kchanLuo** [FlagAlpha/Llama2-Chinese#178]
我进行仓库中的代码对Llama-2-7b-chat-hf进行增量预训练，训练数据是data目录下的csv文件，报错：
[9861 rows x 1 columns]
Traceback (most recent call last):
File "/usr/local/miniconda3/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3653, in get_loc
return self._engine.get_loc(casted_key)
File "pandas/_libs/index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
File "pandas/_libs/index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'file_name'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "pretrain_clm.py", line 616, in <module>
main()
File "pretrain_clm.py", line 303, in main
data_files["train"] = pd.read_csv(data_args.train_files[0])['file_name'].to_list()
File "/usr/local/miniconda3/lib/python3.8/site-packages/pandas/core/frame.py", line 3761, in getitem
indexer = self.columns.get_loc(key)
File "/usr/local/miniconda3/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3655, in get_loc
raise KeyError(key) from err
KeyError: 'file_name'

根据报错将代码中的filename改成和csv文件中一致的text后，报错：

Traceback (most recent call last):
  File "pretrain_clm.py", line 616, in <module>
    main()
  File "pretrain_clm.py", line 317, in main
    raw_datasets = load_dataset(
  File "/usr/local/miniconda3/lib/python3.8/site-packages/datasets/load.py", line 2112, in load_dataset
    builder_instance = load_dataset_builder(
  File "/usr/local/miniconda3/lib/python3.8/site-packages/datasets/load.py", line 1798, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "/usr/local/miniconda3/lib/python3.8/site-packages/datasets/load.py", line 1497, in dataset_module_factory
    raise FileNotFoundError(
FileNotFoundError: Couldn't find a dataset script at /hy-tmp/Llama2-Chinese-main/train/pretrain/<s>Human: 给出一个问题，要求助手回答该问题的时间限制。如果回答超出时间限制，客户应该得到通知。
问题: "一天有多少秒？"时间限制: 10秒
</s><s>Assistant: 一天有86400秒。
</s>/s>.py or any data file in the same directory.

请问如何解决？

**Comment by ZHangZHengEric** [comment]
已修复
