### ISSUE TITLE
完全按照原始代码 但是有这个错误

### ISSUE THREAD

**Issue by xiaomingtx6** [FlagAlpha/Llama2-Chinese#266]

**Comment by xiaomingtx6** [comment]
Traceback (most recent call last):
  File "/gemini/code/finetune_clm_lora.py", line 690, in <module>
    main()
  File "/gemini/code/finetune_clm_lora.py", line 651, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/usr/local/lib/python3.9/dist-packages/transformers/trainer.py", line 1555, in train
    return inner_training_loop(
  File "/usr/local/lib/python3.9/dist-packages/transformers/trainer.py", line 1910, in _inner_training_loop
    self.optimizer.step()
AttributeError: 'DummyOptim' object has no attribute 'step'
