### ISSUE TITLE
安装 Deepspeed时，Unable to pre-compile async_io

### ISSUE THREAD

**Issue by mmhzlrj** [FlagAlpha/Llama2-Chinese#27]
Attempting to remove deepspeed/git_version_info_installed.py
Attempting to remove dist
Attempting to remove build
Attempting to remove deepspeed.egg-info
No hostfile exists at /job/hostfile, installing locally
Building deepspeed wheel
test.c
LINK : fatal error LNK1181: 无法打开输入文件“aio.lib”
DS_BUILD_OPS=1
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
 [WARNING]  One can disable async_io with DS_BUILD_AIO=0
 [ERROR]  Unable to pre-compile async_io
Traceback (most recent call last):
  File "C:\Llama2-Chinese\DeepSpeed\setup.py", line 165, in <module>
    abort(f"Unable to pre-compile {op_name}")
  File "C:\Llama2-Chinese\DeepSpeed\setup.py", line 51, in abort
    assert False, msg
AssertionError: Unable to pre-compile async_io
Error on line 155
Fail to install deepspeed

**Comment by ocheng2005** [comment]
遇到同样的问题 +1
