### ISSUE TITLE
微调时候一直datasets报错是因为什么呀

### ISSUE THREAD

**Issue by Richard-Wth** [FlagAlpha/Llama2-Chinese#82]
Traceback (most recent call last):
  File "/home/wth/anaconda3/envs/llama2/lib/python3.10/site-packages/datasets/builder.py", line 1949, in _prepare_split_single
    num_examples, num_bytes = writer.finalize()
  File "/home/wth/anaconda3/envs/llama2/lib/python3.10/site-packages/datasets/arrow_writer.py", line 598, in finalize
    raise SchemaInferenceError("Please pass `features` or at least one example when writing data")
datasets.arrow_writer.SchemaInferenceError: Please pass `features` or at least one example when writing data

**Comment by wrenchonline** [comment]
训练文件写错了。
