### ISSUE TITLE
部署之后运行RuntimeError

### ISSUE THREAD

**Issue by AlanWangyiran** [FlagAlpha/Llama2-Chinese#86]
报错信息：
 Traceback (most recent call last):
  File "/data/haier/Llama2-Chinese-main/test.py", line 20, in <module>
    generate_ids  = model.generate(**generate_input)
  File "/home/wyr/anaconda3/envs/haier/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/wyr/anaconda3/envs/haier/lib/python3.8/site-packages/transformers/generation/utils.py", line 1588, in generate
    return self.sample(
  File "/home/wyr/anaconda3/envs/haier/lib/python3.8/site-packages/transformers/generation/utils.py", line 2678, in sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

运行代码为：
model = AutoModelForCausalLM.from_pretrained('FlagAlpha/Llama2-Chinese-7b-Chat',device_map='auto',torch_dtype=torch.float16,load_in_8bit=True,cache_dir="/data/haier/Llama2-Chinese-main")
model =model.eval()
tokenizer = AutoTokenizer.from_pretrained('FlagAlpha/Llama2-Chinese-7b-Chat',use_fast=False,cache_dir="/data/haier/Llama2-Chinese-main")
tokenizer.pad_token = tokenizer.eos_token
input_ids = tokenizer(['<s>Human: 介绍一下中国\n</s><s>Assistant: '], return_tensors="pt",add_special_tokens=False).input_ids.to('cuda')        
generate_input = {
    "input_ids":input_ids,
    "max_new_tokens":512,
    "do_sample":True,
    "top_k":50,
    "top_p":0.95,
    "temperature":0.3,
    "repetition_penalty":1.3,
    "eos_token_id":tokenizer.eos_token_id,
    "bos_token_id":tokenizer.bos_token_id,
    "pad_token_id":tokenizer.pad_token_id
}
generate_ids  = model.generate(**generate_input)
text = tokenizer.decode(generate_ids[0])
print(text)

尝试1：
删除  "do_sample":True之后不报错，但输出为很多行<unk><unk><unk><unk><unk>

环境：
pytorch = 2.20.1 transformer = 4.31.0

**Comment by rufeng-h** [comment]
我也是这样的报错，环境和仓库requirements.txt一模一样，cuda版本是12.2

**Comment by rufeng-h** [comment]
仓库中的examples/chat_gradio脚本，跑7b模型正常，跑13b报错，报错信息和楼上一样的，删掉do_sample后推理很慢，输出一堆<unk>

**Comment by rufeng-h** [comment]
> 
我的解决了，我是从外网下载模型到windows系统上，然后U盘拷贝到内网，再上传到服务器，中间不知道哪个环节出问题了，检查文件的md5sum发现不对，重新下载上传就好了

**Comment by rufeng-h** [comment]
> 报错信息：
> 
> > Traceback (most recent call last):
> > File "/data/haier/Llama2-Chinese-main/test.py", line 20, in 
> > generate_ids  = model.generate(**generate_input)
> > File "/home/wyr/anaconda3/envs/haier/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
> > return func(*args, **kwargs)
> > File "/home/wyr/anaconda3/envs/haier/lib/python3.8/site-packages/transformers/generation/utils.py", line 1588, in generate
> > return self.sample(
> > File "/home/wyr/anaconda3/envs/haier/lib/python3.8/site-packages/transformers/generation/utils.py", line 2678, in sample
> > next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
> > RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
> 
> 运行代码为：
> 
> ```
> model = AutoModelForCausalLM.from_pretrained('FlagAlpha/Llama2-Chinese-7b-Chat',device_map='auto',torch_dtype=torch.float16,load_in_8bit=True,cache_dir="/data/haier/Llama2-Chinese-main")
> model =model.eval()
> tokenizer = AutoTokenizer.from_pretrained('FlagAlpha/Llama2-Chinese-7b-Chat',use_fast=False,cache_dir="/data/haier/Llama2-Chinese-main")
> tokenizer.pad_token = tokenizer.eos_token
> input_ids = tokenizer(['<s>Human: 介绍一下中国\n</s<s>Assistant: '], return_tensors="pt",add_special_tokens=False).input_ids.to('cuda')        
> generate_input = {
>     "input_ids":input_ids,
>     "max_new_tokens":512,
>     "do_sample":True,
>     "top_k":50,
>     "top_p":0.95,
>     "temperature":0.3,
>     "repetition_penalty":1.3,
>     "eos_token_id":tokenizer.eos_token_id,
>     "bos_token_id":tokenizer.bos_token_id,
>     "pad_token_id":tokenizer.pad_token_id
> }
> generate_ids  = model.generate(**generate_input)
> text = tokenizer.decode(generate_ids[0])
> print(text)
> ```
> 
> 尝试1： 删除 "do_sample":True之后不报错，但输出为很多行 `Assistant: 1 Stanis2<unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk>`
> 
> 环境： pytorch = 2.20.1 transformer = 4.31.0

我的解决了，我是从外网下载模型到windows系统上，然后U盘拷贝到内网，再上传到服务器，中间不知道哪个环节出问题了，检查文件的md5sum发现不对，重新下载上传就好了
